/// \file GameDefines.h
/// \brief Game specific defines.

#pragma once

#include "Defines.h"

/// \brief Sprite type.
///
/// Note: NUM_SPRITES must be last.

enum eSpriteType{
  TILE_SPRITE, PLAYER_SPRITE, TURRET_SPRITE, SPIKES_SPRITE, BRIDGE_SPRITE, END_SPRITE, DEATH_SPRITE, ONE_SPRITE, TWO_SPRITE, THREE_SPRITE, STAR_SPRITE, BLANKSTAR_SPRITE,
  BULLET_SPRITE, BULLET2_SPRITE, GREENLINE_SPRITE, SMOKE_SPRITE, BLOOD_SPRITE,
  SPARK_SPRITE, WARRIOR_SPRITE,MINER_SPRITE, AMBER_SPRITE, GOLD_SPRITE, SAPPHIRE_SPRITE, EMERALD_SPRITE, 
	AMETHYST_SPRITE, RUBY_SPRITE, DIAMOND_SPRITE, BACON_SPRITE,
  PLATFORM_SPRITE, PLAY_SPRITE, ROT_SPRITE, FIN_SPRITE, MENU1_SPRITE, ISPIKE_SPRITE, IBRIDGE_SPRITE, LGOBLIN_SPRITE, RGOBLIN_SPRITE, GOBLINARM_SPRITE, GAMEOVER_SPRITE,
  MSELECT_SPRITE, WEB_SPRITE, SPIDER_SPRITE, SWITCH_SPRITE, DOOR_SPRITE, SHADE_SPRITE, BACK_SPRITE, RESULTSCREEN_SPRITE, ILGOBLIN_SPRITE, IRGOBLIN_SPRITE, BUTTON_SPRITE, MOVING_SPRITE,
  NUM_SPRITES//MUST BE LAST
}; //eSpriteType
